### ISSUE TITLE
Slides页面大小不一致

### ISSUE THREAD

**Issue by Yikai-Wang** [zhoubolei/introRL#3]
周老师您好，您放出的slides里chapter1，8，9和chapter2-7采用了两种页面大小，如果想把所有slides合并成一个PDF文件会造成chapter2-7宽度过小的问题，能否提供相同页面大小的PDF呢？谢谢！

**Comment by foocker** [comment]
这两个是ppt，其他都是beamer，本质不一样。

**Comment by foocker** [comment]
> 周老师您好，您放出的slides里chapter1，8，9和chapter2-7采用了两种页面大小，如果想把所有slides合并成一个PDF文件会造成chapter2-7宽度过小的问题，能否提供相同页面大小的PDF呢？谢谢！

这两个是ppt，其他都是beamer，本质不一样。
