### ISSUE TITLE
possible typos in lecture 2

### ISSUE THREAD

**Issue by szcf-weiya** [zhoubolei/introRL#5]
Hi Prof. Zhou,
On p31, you write

![image](https://user-images.githubusercontent.com/13688320/85949071-1eff6900-b987-11ea-944e-f00969b16733.png)
For my understanding, it seems that the action should be summarized out for the stochastic policy, although it is fine to omit the summation of action for the deterministic policy on p30. That might be a typo, or am I missing something?

**Comment by zhoubolei** [comment]
Thanks. Corrected.
